# Package Overview
package_name: plant_disease_model
 
# Data Files
clearml:
  project_name: "Harit_CapStone_Project"
  dataset: Harit_DataSet
  output_dir: "./dataset"
  dataset_version: v1.0.0
  checkpoint_name: "Harit_model_checkpoint.keras"
  model_id: b88b00c23dc54928a2c51b02de26fd38

# Data Files
data_dir: ./dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/
test_data_dir: ./dataset/test/


pipeline_name: plant_disease_model
pipeline_save_file: plant_disease_model_v
 
# Set train/test split
test_size: 0.20
 
# Set the random seed
random_state: 42
 
# Alogrithm parameters
epochs: 2
batch_size: 64